In [1]:
import pandas as pd
import pickle

In [2]:
%%time
may = pd.read_csv('../data/may.csv')
may.head()

Wall time: 16.1 s

,pubdatetime,latitude,longitude,sumdid,sumdtype,chargelevel,sumdgroup,costpermin,companyname
0,2019-05-01 00:01:41.247000,36.136822,-86.799877,PoweredLIRL1,Powered,93.0,scooter,0.0,Bird
1,2019-05-01 00:01:41.247000,36.191252,-86.772945,PoweredXWRWC,Powered,35.0,scooter,0.0,Bird
2,2019-05-01 00:01:41.247000,36.144752,-86.806293,PoweredMEJEH,Powered,90.0,scooter,0.0,Bird
3,2019-05-01 00:01:41.247000,36.162056,-86.774688,Powered1A7TC,Powered,88.0,scooter,0.0,Bird
4,2019-05-01 00:01:41.247000,36.150973,-86.783109,Powered2TYEF,Powered,98.0,scooter,0.0,Bird

In [3]:
may.info() ##20292503 rows, 9 columns, note pubdatetime is an object and needs to be changed to datetime

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20292503 entries, 0 to 20292502
Data columns (total 9 columns):
 #   Column       Dtype
---  ------       -----
 0   pubdatetime  object
 1   latitude     float64
 2   longitude    float64
 3   sumdid       object
 4   sumdtype     object
 5   chargelevel  float64
 6   sumdgroup    object
 7   costpermin   float64
 8   companyname  object
dtypes: float64(4), object(5)
memory usage: 1.4+ GB

In [4]:
may.isnull().sum()##CHARGE LEVEL COLUMN HAS 283 NULLS

pubdatetime      0
latitude         0
longitude        0
sumdid           0
sumdtype         0
chargelevel    283
sumdgroup        0
costpermin       0
companyname      0
dtype: int64

In [5]:
##may.info()

In [6]:
##may.describe()

In [7]:
may.companyname.unique()

array(['Bird', 'Lyft', 'Gotcha', 'Lime', 'Spin', 'Jump', 'Bolt'],
      dtype=object)

In [8]:
company_dict = {'Bird':'Bi', 'Lyft': 'Ly', 'Gotcha': 'G', 'Lime': 'Li', 'Spin': 'S', 'Jump': 'J', 'Bolt': 'Bo'}

In [9]:
may.companyname = may.companyname.replace(company_dict)##replaced company name with 2 letter name dictionary

In [10]:
##may.pubdatetime = pd.to_datetime(may.pubdatetime)##CHANGES PUBDATETIME COLUMN FROM OBJECT TO DATE TIME
may.pubdatetime = pd.to_datetime(may.pubdatetime)

In [11]:
##may.date=pd.to_datetime(may.pubdatetime).dt.date

In [13]:
may['year'] = may['pubdatetime'].dt.year

may['month'] = may['pubdatetime'].dt.month

may['day'] = may['pubdatetime'].dt.day

may['hour'] = may['pubdatetime'].dt.hour
may['min'] = may['pubdatetime'].dt.minute
##may['sec'] = may['pubdatetime'].dt.seconds

In [ ]:
##import datetime
##from datetime import datetime
##my_date = datetime.strptime(pubdatetime, "%Y-%m-%d")
##my_date
##may['date'] = [d.date() for d in may['pubdatetime']]
##may['time'] = [d.time() for d in may['pubdatetime']]

##import datetime

# this line converts the string object in Timestamp object
##may['DateTime'] = [datetime.datetime.strptime(d, "%Y-%m-%d %H:%M") for d in may["pubdatetime"]]

# extracting date from timestamp
##may['Date'] = [datetime.datetime.date(d) for d in may['pubdatetime']] 

# extracting time from timestamp
##may['Time'] = [datetime.datetime.time(d) for d in may['pubdatetime']]

In [14]:
may.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20292503 entries, 0 to 20292502
Data columns (total 14 columns):
 #   Column       Dtype
---  ------       -----
 0   pubdatetime  datetime64[ns]
 1   latitude     float64
 2   longitude    float64
 3   sumdid       object
 4   sumdtype     object
 5   chargelevel  float64
 6   sumdgroup    object
 7   costpermin   float64
 8   companyname  object
 9   year         int64
 10  month        int64
 11  day          int64
 12  hour         int64
 13  min          int64
dtypes: datetime64[ns](1), float64(4), int64(5), object(4)
memory usage: 2.1+ GB

In [15]:
may.sumdgroup.unique() ##produces all the unique values in the sumdgroup column

array(['scooter', 'Scooter', 'bicycle'], dtype=object)

In [16]:
may.sumdtype.unique() ##produces all the unique values in the sumdtype column

array(['Powered', 'Standard'], dtype=object)

In [17]:
may_scooters = may.loc[may.sumdgroup.isin(['scooter', 'Scooter'])] ##FILTERS DATAFRAME TO ONLY SHOW ROWS WHERE SUMDGROUP = SCOOTERS

In [18]:
may_scooters.companyname.value_counts() ##gives the count of scooters by company

Li    7111655
Bi    4334006
Ly    3112581
J     2984630
S     1301001
G      915314
Bo     524395
Name: companyname, dtype: int64

In [19]:
##may_scooters = may_scooters[['pubdatetime', 'latitude', 'longitude', 'chargelevel', 'companyname']] ##drops columns costpermin from dataframe

In [20]:
may_scooters = may.drop(columns=['costpermin']) ##drops columns chargelevel and costpermin from dataframe

In [21]:
may_scooters.dropna(inplace=True) ##dropping all null rows

In [22]:
may_scooters.tail(30)

,pubdatetime,latitude,longitude,sumdid,sumdtype,chargelevel,sumdgroup,companyname,year,month,day,hour,min
20292473,2019-05-31 23:58:27.240,36.120970,-86.776146,PoweredZVJWKTABQJ25L,Powered,28.0,scooter,Li,2019,5,31,23,58
20292474,2019-05-31 23:58:27.240,36.129974,-86.780385,PoweredFVUZ4QWL4TK6E,Powered,64.0,scooter,Li,2019,5,31,23,58
20292475,2019-05-31 23:58:27.240,36.124556,-86.788822,Powered7UN7P27A5HR5H,Powered,62.0,scooter,Li,2019,5,31,23,58
20292476,2019-05-31 23:58:27.240,36.127037,-86.777519,PoweredZ72S7KBKVZWU7,Powered,69.0,scooter,Li,2019,5,31,23,58
20292477,2019-05-31 23:58:27.240,36.129797,-86.775474,PoweredJREQVMOESVGFU,Powered,41.0,scooter,Li,2019,5,31,23,58
20292478,2019-05-31 23:58:27.240,36.126900,-86.777635,PoweredZKXGQSVDO5MSH,Powered,47.0,scooter,Li,2019,5,31,23,58
20292479,2019-05-31 23:58:27.240,36.126730,-86.778222,Powered6DUTKKBTR5HSP,Powered,57.0,scooter,Li,2019,5,31,23,58
20292480,2019-05-31 23:58:27.240,36.127732,-86.789159,PoweredXMLNIU65PJUYC,Powered,85.0,scooter,Li,2019,5,31,23,58
20292481,2019-05-31 23:58:27.240,36.125782,-86.788864,PoweredOQYNOUBQPNGUS,Powered,25.0,scooter,Li,2019,5,31,23,58
20292482,2019-05-31 23:58:27.240,36.127703,-86.789172,PoweredUG2O3VTHVVO4K,Powered,55.0,scooter,Li,2019,5,31,23,58
20292483,2019-05-31 23:58:27.240,36.126457,-86.789675,Powered4WOKR5XFN26KV,Powered,87.0,scooter,Li,2019,5,31,23,58
20292484,2019-05-31 23:58:27.240,36.126391,-86.775422,PoweredGI5OMRWPRDANJ,Powered,57.0,scooter,Li,2019,5,31,23,58
20292485,2019-05-31 23:58:27.240,36.132976,-86.798867,Powered6CNUM33L6PLLF,Powered,50.0,scooter,Li,2019,5,31,23,58
20292486,2019-05-31 23:58:27.243,36.121644,-86.775497,PoweredKST5FB2VTIYWL,Powered,44.0,scooter,Li,2019,5,31,23,58
20292487,2019-05-31 23:58:27.243,36.122967,-86.776069,PoweredSQWMJWTIGM6DS,Powered,60.0,scooter,Li,2019,5,31,23,58
20292488,2019-05-31 23:58:27.243,36.109752,-86.765515,PoweredHI5KWQSV2YQ54,Powered,63.0,scooter,Li,2019,5,31,23,58
20292489,2019-05-31 23:58:27.243,36.115655,-86.764993,PoweredFR3FK5ZFAH6GV,Powered,75.0,scooter,Li,2019,5,31,23,58
20292490,2019-05-31 23:58:27.243,36.109843,-86.765417,Powered6IG7XXTA4EBYH,Powered,38.0,scooter,Li,2019,5,31,23,58
20292491,2019-05-31 23:58:27.243,36.115631,-86.764978,Powered23TSUHG3WSN3E,Powered,69.0,scooter,Li,2019,5,31,23,58
20292492,2019-05-31 23:58:27.243,36.108510,-86.764921,PoweredQOW23KD6JPIJZ,Powered,58.0,scooter,Li,2019,5,31,23,58
20292493,2019-05-31 23:58:27.243,36.122375,-86.775722,PoweredHICJ5XYHBAW5I,Powered,60.0,scooter,Li,2019,5,31,23,58
20292494,2019-05-31 23:58:27.243,36.121613,-86.775351,PoweredXZH7USFBU76DX,Powered,94.0,scooter,Li,2019,5,31,23,58
20292495,2019-05-31 23:58:27.243,36.120440,-86.777199,PoweredSZAWEG5FWAI6V,Powered,56.0,scooter,Li,2019,5,31,23,58
20292496,2019-05-31 23:58:27.243,36.121584,-86.775493,PoweredU6FP6ZXZ6JRTC,Powered,94.0,scooter,Li,2019,5,31,23,58
20292497,2019-05-31 23:58:43.000,36.147400,-86.811700,Poweredf0c59838-3392-5ea9-9a8f-d680bc8ac344,Powered,71.0,scooter,J,2019,5,31,23,58
20292498,2019-05-31 23:59:42.000,36.163900,-86.782300,Poweredbb60ef04-c719-597f-805f-20978964fd8c,Powered,49.0,scooter,J,2019,5,31,23,59
20292499,2019-05-31 23:59:42.000,36.160600,-86.776800,Powered9f5743ed-7f81-539b-9e37-6503d54445d3,Powered,68.0,scooter,J,2019,5,31,23,59
20292500,2019-05-31 23:59:42.000,36.160600,-86.776900,Powered5744d1db-3bbe-55e5-9a23-a93828ba54fc,Powered,53.0,scooter,J,2019,5,31,23,59
20292501,2019-05-31 23:59:42.000,36.162400,-86.774500,Poweredad1d6d3b-162a-5bec-bffd-cac4ac8dee1c,Powered,42.0,scooter,J,2019,5,31,23,59
20292502,2019-05-31 23:59:42.000,36.151900,-86.798500,Powered8505008e-97c9-5003-8975-2ea6b2634fa0,Powered,76.0,scooter,J,2019,5,31,23,59

In [23]:
may_scooters.info()
##Original info before drop of null rows, RangeIndex: 20292503 entries, 0 to 20292502, Data columns (total 9 columns):

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20292220 entries, 0 to 20292502
Data columns (total 13 columns):
 #   Column       Dtype
---  ------       -----
 0   pubdatetime  datetime64[ns]
 1   latitude     float64
 2   longitude    float64
 3   sumdid       object
 4   sumdtype     object
 5   chargelevel  float64
 6   sumdgroup    object
 7   companyname  object
 8   year         int64
 9   month        int64
 10  day          int64
 11  hour         int64
 12  min          int64
dtypes: datetime64[ns](1), float64(3), int64(5), object(4)
memory usage: 2.1+ GB

In [24]:
may_scooters.to_pickle("../data/may.pkl")

In [25]:
%%time
may_test = pd.read_pickle("../data/may.pkl")

Wall time: 5.3 s

In [26]:
may_scooters.sumdid.unique()

array(['PoweredLIRL1', 'PoweredXWRWC', 'PoweredMEJEH', ...,
       'PoweredS26HB', 'PoweredWVFVTYLWIVLI7', 'Powered6Y1U7'],
      dtype=object)

In [27]:
may_scooters.sumdid.nunique() ##count the number of unique sumdid

8302

In [28]:
print(may_scooters['sumdid'].value_counts()) ##the count of each of the distinct values of a specific column
##https://datascienceparichay.com/article/pandas-count-of-unique-values-in-each-column/

PoweredIE7H5RIN474PE     8921
StandardNW5HJFO4R32LY    8921
PoweredUK65LOU3K5N7G     8748
PoweredIOHG2G3XKATUL     8576
PoweredJCKMQCAL2SSNJ     8521
                         ...
PoweredGJYGPDVTFXRH7        1
PoweredYEBSU                1
PoweredCW742BQMJ3XHN        1
PoweredCI6VKIK2KOFMC        1
PoweredN4YI2A7RXZQLY        1
Name: sumdid, Length: 8302, dtype: int64

In [29]:
##7 SCOOTER COMPANIES, 8304 SCOOTERS,

In [30]:
may_group=may_scooters.groupby(['companyname'])['sumdid'].nunique()

In [31]:
may_group

companyname
Bi    3064
Bo     346
G      223
J      976
Li    1632
Ly    1376
S      685
Name: sumdid, dtype: int64

In [32]:
##may_scooters.plot()

Error in callback <function flush_figures at 0x000002528C104040> (for post_execute):

KeyboardInterrupt:

In [ ]:
##import matplotlib.pyplot as plt
##import seaborn as sns
##%matplotlib inline

In [ ]:
#set the seaborn theme, style, color palette
#sns.set(style="ticks", color_codes=True)

#make a correlation plot that looks at each variables relationship with every other variable
#and plots the distribution of each variable along the diagonal
#sns.pairplot(may_scooters);

In [41]:
duplicate_rows = may_scooters[may_scooters.duplicated()]
## Select duplicate rows except first occurrence based on all columns
##duplicateRowsDF = dfObj[dfObj.duplicated()]
##print("Duplicate Rows except first occurrence based on all columns are :")
##print(duplicateRowsDF)

In [42]:
print("Duplicate Rows except first occurrence based on all columns are:")

Duplicate Rows except first occurrence based on all columns are:

In [43]:
print(duplicate_rows)

Empty DataFrame
Columns: [pubdatetime, latitude, longitude, sumdid, sumdtype, chargelevel, sumdgroup, companyname, year, month, day, hour, min]
Index: []

In [ ]:
##https://thispointer.com/pandas-find-duplicate-rows-in-a-dataframe-based-on-all-or-selected-columns-using-dataframe-duplicated-in-python/

In [44]:
may_dead=may_scooters.loc[(may_scooters['chargelevel'] == 0.00)]

In [45]:
may_dead

,pubdatetime,latitude,longitude,sumdid,sumdtype,chargelevel,sumdgroup,companyname,year,month,day,hour,min
1077,2019-05-01 00:04:48.030,36.162910,-86.776332,Powered406,Powered,0.0,Scooter,G,2019,5,1,0,4
1084,2019-05-01 00:04:48.030,36.152102,-86.762997,Powered785,Powered,0.0,Scooter,G,2019,5,1,0,4
1093,2019-05-01 00:04:48.030,36.156370,-86.786350,Powered412,Powered,0.0,Scooter,G,2019,5,1,0,4
1095,2019-05-01 00:04:48.030,36.121324,-86.770482,Powered826,Powered,0.0,Scooter,G,2019,5,1,0,4
1096,2019-05-01 00:04:48.030,36.121522,-86.770209,Powered769,Powered,0.0,Scooter,G,2019,5,1,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20291457,2019-05-31 23:58:00.927,36.153768,-86.783705,Powered1572748,Powered,0.0,Scooter,S,2019,5,31,23,58
20291578,2019-05-31 23:58:00.927,36.210910,-86.736240,Powered1590780,Powered,0.0,Scooter,S,2019,5,31,23,58
20291808,2019-05-31 23:58:27.210,36.133764,-86.791866,PoweredUK65LOU3K5N7G,Powered,0.0,scooter,Li,2019,5,31,23,58
20291887,2019-05-31 23:58:27.210,36.133778,-86.791849,PoweredKZQINR7YHPOLL,Powered,0.0,scooter,Li,2019,5,31,23,58
20292041,2019-05-31 23:58:27.217,36.161245,-86.781209,PoweredJ36KZF4FQ7LQB,Powered,0.0,scooter,Li,2019,5,31,23,58

In [46]:
Powered406=may_dead.loc[(may_dead['sumdid']=='Powered406')]
Powered406

,pubdatetime,latitude,longitude,sumdid,sumdtype,chargelevel,sumdgroup,companyname,year,month,day,hour,min
1077,2019-05-01 00:04:48.030,36.162910,-86.776332,Powered406,Powered,0.0,Scooter,G,2019,5,1,0,4
3427,2019-05-01 00:09:48.257,36.162910,-86.776332,Powered406,Powered,0.0,Scooter,G,2019,5,1,0,9
5498,2019-05-01 00:14:48.537,36.162910,-86.776332,Powered406,Powered,0.0,Scooter,G,2019,5,1,0,14
7752,2019-05-01 00:19:48.763,36.162910,-86.776332,Powered406,Powered,0.0,Scooter,G,2019,5,1,0,19
9931,2019-05-01 00:24:49.147,36.162910,-86.776332,Powered406,Powered,0.0,Scooter,G,2019,5,1,0,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18824347,2019-05-30 13:55:56.267,36.162352,-86.774037,Powered406,Powered,0.0,Scooter,G,2019,5,30,13,55
18828158,2019-05-30 14:00:56.367,36.162352,-86.774037,Powered406,Powered,0.0,Scooter,G,2019,5,30,14,0
18831987,2019-05-30 14:05:56.797,36.162352,-86.774037,Powered406,Powered,0.0,Scooter,G,2019,5,30,14,5
18835706,2019-05-30 14:10:56.923,36.162352,-86.774037,Powered406,Powered,0.0,Scooter,G,2019,5,30,14,10
18839656,2019-05-30 14:15:57.053,36.162352,-86.774037,Powered406,Powered,0.0,Scooter,G,2019,5,30,14,15

In [47]:
# Select all duplicate rows based on multiple column names in list
duplicate_location = Powered406[Powered406.duplicated(['latitude', 'longitude'])]

In [48]:
duplicate_location ##in Powered406 there are 868 rows. when looking at duplicate locations for Powered406 662 rows

,pubdatetime,latitude,longitude,sumdid,sumdtype,chargelevel,sumdgroup,companyname,year,month,day,hour,min
3427,2019-05-01 00:09:48.257,36.162910,-86.776332,Powered406,Powered,0.0,Scooter,G,2019,5,1,0,9
5498,2019-05-01 00:14:48.537,36.162910,-86.776332,Powered406,Powered,0.0,Scooter,G,2019,5,1,0,14
7752,2019-05-01 00:19:48.763,36.162910,-86.776332,Powered406,Powered,0.0,Scooter,G,2019,5,1,0,19
9931,2019-05-01 00:24:49.147,36.162910,-86.776332,Powered406,Powered,0.0,Scooter,G,2019,5,1,0,24
12097,2019-05-01 00:29:49.140,36.162910,-86.776332,Powered406,Powered,0.0,Scooter,G,2019,5,1,0,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18824347,2019-05-30 13:55:56.267,36.162352,-86.774037,Powered406,Powered,0.0,Scooter,G,2019,5,30,13,55
18828158,2019-05-30 14:00:56.367,36.162352,-86.774037,Powered406,Powered,0.0,Scooter,G,2019,5,30,14,0
18831987,2019-05-30 14:05:56.797,36.162352,-86.774037,Powered406,Powered,0.0,Scooter,G,2019,5,30,14,5
18835706,2019-05-30 14:10:56.923,36.162352,-86.774037,Powered406,Powered,0.0,Scooter,G,2019,5,30,14,10
18839656,2019-05-30 14:15:57.053,36.162352,-86.774037,Powered406,Powered,0.0,Scooter,G,2019,5,30,14,15

In [49]:
grouped_multiple=may_scooters.groupby(['latitude', 'longitude'])['sumdid'].nunique()

In [39]:
##may_group=may_scooters.groupby(['companyname'])['sumdid'].nunique()

In [50]:
grouped_multiple

latitude   longitude
0.000000    0.000000     18
32.789116  -79.940267     1
32.828031  -79.954386     1
32.859748  -79.992988     1
33.315812  -80.544998     1
                         ..
36.616640  -87.284660     1
           -87.284570     1
36.616650  -87.284660     1
36.616670  -87.284640     1
36.616700  -87.284640     1
Name: sumdid, Length: 6942841, dtype: int64